from typing import Optional, List
from pydantic import BaseModel, Field
from datetime import datetime

# ==========================================================
# PART 1: THE CART ITEMS (The individual rows on a receipt)
# ==========================================================

class SalesItemCreate(BaseModel):
    product_id: int = Field(..., description="The database ID of the product being bought")
    quantity: int = Field(..., gt=0, description="The receptionist inputs this. Must be 1 or more.")
    # Notice: No unit_price here! The system fetches that from the Product table securely.


class SalesItemResponse(BaseModel):
    id: int
    product_id: int
    quantity: int
    unit_price: float  # Outbound shows the price frozen in time for this specific transaction

    class Config:
        from_attributes = True


# ==========================================================
# PART 2: THE MAIN SALE (The actual checkout transaction)
# ==========================================================

class SaleCreate(BaseModel):
    payment_method: str = Field(..., description="Must be 'cash', 'card', or 'transfer'")
    
    # This nests the cart items list right inside the checkout form
    items: List[SalesItemCreate] = Field(..., min_items=1, description="The cart cannot be empty")


class SaleResponse(BaseModel):
    id: int
    receipt_number: str  # Generated by the system
    total_amount: float  # Calculated by the system (quantity * unit_price)
    payment_method: str
    timestamp: datetime  # Auto-stamped by the system
    
    # This prints out the full list of items on the final digital receipt
    sales_items: List[SalesItemResponse]

    class Config:
        from_attributes = True